services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: src/Products.Api/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - 5000:8080
      - 5001:8081

  postgres:
    image: postgres:latest
    container_name: PostgreSql
    environment:
      - POSTGRES_DB=commerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMq
    hostname: rabbitmq
    volumes:
      - ./.containers/rabbitmq/data/:/var/lib/rabbitmq
      - ./.containers/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672
      - 5672:5672

  seq:
    image: datalust/seq:latest
    container_name: Seq
    volumes:
      - ./.containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
